# Generated by Django 3.2.11 on 2022-02-03 06:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('media_file', models.FileField(upload_to='')),
                ('course', models.CharField(choices=[('BSC', 'Bachelor of Science (BSC)'), ('BE', 'Bachelor of Engineering (BE)'), ('BCA', 'Bachelor of Computer Applications (BCA)'), ('BPT', 'Bachelor of Physiotherapy (BPT)'), ('CCC', 'Course on Computer Concepts (CCC)'), ('BA', 'Bachelor of Arts (BA)'), ('BCOM', 'Bachelor of Commerce (BCOM)'), ('MBBS', 'Bachelor of Medicine (MBBS)')], default='BE', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('CE', 'Computer Engineering'), ('ME', 'Mechanical Engineering'), ('PE', 'Power Engineering'), ('EE', 'Electrical Engineering')], max_length=2)),
                ('start_first_year', models.IntegerField()),
                ('detain_year', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_year_spi', models.IntegerField(blank=True, null=True)),
                ('second_year_spi', models.IntegerField(blank=True, null=True)),
                ('third_year_spi', models.IntegerField(blank=True, null=True)),
                ('fourth_year_spi', models.IntegerField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
